// Mock long URL for the homepage + /short-links hero visual. Deliberately
// messy (UTM-tagged campaign) so the clean `anch.to/{slug}` payoff feels
// earned. The short URL is computed at render time: on anch.to itself the
// slug is always auto-generated by the CSPRNG from SAFE_ALPHABET (see
// src/lib/utils/slug-alphabet.ts) — custom slugs are Pro-gated and only
// resolve through a user-owned short domain. Hardcoding a cute slug like
// "launch" misrepresents what a free-tier visitor actually gets, so the
// visual regenerates a fresh random slug each loop cycle.
export const LONG_URL = "https://example.com/summer-launch?utm_source=newsletter&utm_campaign=2026";

/** Prefix applied to every generated short URL the typewriter renders. */
export const SHORT_URL_PREFIX = "anch.to/";

/** Slug length. Matches `DEFAULT_START_LENGTH` in `short-slug.ts` — the
 *  length a real first-time shortener user would receive on anch.to today. */
export const SHORT_URL_SLUG_LENGTH = 5;

// Timings (ms). Typing-slower-than-deleting matches natural "oh wait, let me
// fix that" rhythm, and the longer pause on the short URL gives the viewer
// time to appreciate the payoff before the loop restarts.
export const TYPE_SPEED_MS = 40;
export const DELETE_SPEED_MS = 20;
export const PAUSE_LONG_MS = 1500;
export const PAUSE_SHORT_MS = 2500;

export type Phase = "deleting-long" | "deleting-short" | "pause-long" | "pause-short" | "typing-long" | "typing-short";
